# -*- coding: utf-8 -*-
"""2nd Day Assignment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qV6YJvHIaOju_ffKMwKNwT-e5KKYeUtP
"""

def age_group(age):
  if age < 18:
    return "You are a minor"
  elif age >= 18 and age < 65:
    return "You are an adult"
  else:
    return "You are a senior"

def main():
  age = int(input("Enter your age: "))
  print(age_group(age))

if __name__ == "__main__":
  main()